version: 2

jobs:
  lint:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run: apt update
      - run: apt install -y python3-pip
      - run: pip3 install -U black flake8
      - run: LC_ALL=C.UTF-8 black --check setup.py tikzplotlib/ test/*.py
      - run: flake8 setup.py tikzplotlib/ test/*.py
  build:
    working_directory: ~/work
    docker:
      - image: ubuntu:18.04
    steps:
      - run: apt update
      # <https://stackoverflow.com/a/44333806/353337>
      - run: DEBIAN_FRONTEND=noninteractive apt install tzdata
      - run: apt install -y texlive-latex-base texlive-latex-extra python3-pip python3-tk python3-scipy
      - run: pip3 install -U pytest pytest-cov excode
      - checkout
      - run: cd ~/work
      - run: excode README.md test/zzz_readme_test.py --filter python,test
      - run: pip3 install -r test_requirements.txt
      - run: pip3 install .[all]
      - run: pip3 check
      # The actual test
      - run: cd test/ && MPLBACKEND=Agg pytest --cov tikzplotlib
      # submit to codecov
      - run: apt install -y curl
      - run: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  lint_and_build:
    jobs:
      - lint
      - build
